{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Turno",
        "Service": "/ReporteDiarioMDK/Services/ReporteDiarioMDK.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "descripcion": "#Control:descripcion/#Value",
        "hora_inicial": "#Control:hora_inicial/#Value",
        "hora_fin": "#Control:hora_fin/#Value",
        "vigente": "#Control:vigente/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ReporteDiarioMDK/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ReporteDiarioMDK/Actions/UpdateEntityFailureMessage.action"
}