{
    "CreateLinks": [],
    "OnFailure": "/ReporteDiarioMDK/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ReporteDiarioMDK/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "param": "#Control:param/#Value",
        "valor": "#Control:valor/#Value",
        "glosa": "#Control:glosa/#Value",
        "descripcion": "#Control:descripcion/#Value",
        "vigente": "#Control:vigente/#Value"
    },
    "Target": {
        "EntitySet": "Parametro",
        "Service": "/ReporteDiarioMDK/Services/ReporteDiarioMDK.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}