{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Predio",
        "Service": "/ReporteDiarioMDK/Services/ReporteDiarioMDK.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "zona": "#Control:zona/#Value",
        "rol": "#Control:rol/#Value",
        "descripcion": "#Control:descripcion/#Value",
        "vigente": "#Control:vigente/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ReporteDiarioMDK/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ReporteDiarioMDK/Actions/UpdateEntityFailureMessage.action"
}